### ISSUE TITLE
Parser error during "Loading string table..."

### ISSUE THREAD

**Issue by bm01** [TruePikachu/stationDump#8]
> Loading cat/dat database...
> Loading string table...
> Entity: line 20630: parser error : XML declaration allowed only at the start of the document
> <?xml version="1.0" encoding="UTF-8" ?>
> Entity: line 20631: parser error : Extra content at the end of the document
> <language id="49">

Feel free to ask for more informations as I don't know which kind would be relevant.

**Comment by TruePikachu** [comment]
I'm unable to confirm on Rebirth 3.53. If you extract the /t/0001-L044.xml file from the .cat/.dat packages, does it have an extra decleration on line 20630?
I just pushed a commit to master which will give a bit more information, specifically telling _which_ pack it is trying to read the file from.

**Comment by bm01** [comment]
Here's the new report (removed duplicates):

> File information (from CatDatDB):
> name="t/0001-L044.xml" size=1654391 date=1654391 hash=13005730404f0538aebb6e919b
> a634da at C:\Program Files (x86)\Steam\steamapps\common\X Rebirth/09.dat+39971200
> Entity: line 20630: parser error : XML declaration allowed only at the start of the document
> <?xml version="1.0" encoding="UTF-8" ?>
> Entity: line 20631: parser error : Extra content at the end of the document
> <language id="49">

There's nothing at that line after extraction (end of file).
Similar result if I tell it to search for a different language.

**Comment by TruePikachu** [comment]
Well, that is the exact same version of the 0001-L044.xml that I have, at least according to the 09.cat file. My theory is that the Perl read() in your setup is reading characters with a size which isn't 1 byte. I just switched over to use the sysread() instead, which will guarentee byte-based I/O.

**Comment by bm01** [comment]
Sorry for the late feedback, issue solved!
